# Generated by Django 3.0.7 on 2020-06-21 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_city_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='url',
        ),
    ]
