# Generated by Django 3.0.7 on 2020-06-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_city_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='url',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
