# Generated by Django 3.0.7 on 2020-06-23 01:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20200622_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 1', regex='^.{1}$')], verbose_name='Title'),
        ),
    ]
